<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table [
<!ELEMENT table (row+)>
<!ELEMENT row (type, token, name, wnks)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT token (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT wnks (#PCDATA)>
]>
<table>
<row><type>ua</type><token>80legs</token><name>80 Legs</name><wnks>1</wnks></row>
<row><type>ua</type><token>abonti</token><name>Abonti</name><wnks>1</wnks></row>
<row><type>ua</type><token>acoonbot</token><name>Acoon</name><wnks>1</wnks></row>
<row><type>ua</type><token>aghaven.com</token><name>AgBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>ahrefsbot</token><name>AhrefsBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>aiderss.com</token><name>AideRSS</name><wnks>1</wnks></row>
<row><type>ua</type><token>ia_archiver</token><name>Alexa</name><wnks>1</wnks></row>
<row><type>ua</type><token>amznkassocbot</token><name>AMZNKAssocBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>archive.org_bot</token><name>Archive.org</name><wnks>1</wnks></row>
<row><type>ua</type><token>teoma</token><name>Ask.com/Teoma</name><wnks>1</wnks></row>
<row><type>ua</type><token>backlinktest</token><name>BackLinkTest</name><wnks>1</wnks></row>
<row><type>ua</type><token>baidu.com/search</token><name>BaiduSpider</name><wnks>1</wnks></row>
<row><type>ua</type><token>crawler.bazqux</token><name>Bazqux</name><wnks>1</wnks></row>
<row><type>ua</type><token>beetlebot</token><name>Beetle</name><wnks>1</wnks></row>
<row><type>ua</type><token>bendercrawler</token><name>Bender</name><wnks>1</wnks></row>
<row><type>ua</type><token>benderthewebrobot</token><name>Bender</name><wnks>1</wnks></row>
<row><type>ua</type><token>betabot</token><name>BetaBotAustria</name><wnks>1</wnks></row>
<row><type>ua</type><token>bigbozzbot</token><name>BigBozz</name><wnks>1</wnks></row>
<row><type>ua</type><token>bingpreview</token><name>BingPreview</name><wnks>1</wnks></row>
<row><type>ua</type><token>bintellibot</token><name>BinTelli</name><wnks>1</wnks></row>
<row><type>ua</type><token>bixocrawler</token><name>Bixo</name><wnks>1</wnks></row>
<row><type>ua</type><token>biz360.com</token><name>Biz360</name><wnks>1</wnks></row>
<row><type>ua</type><token>blekkobot</token><name>Blekko</name><wnks>1</wnks></row>
<row><type>ua</type><token>blexbot</token><name>BLEX</name><wnks>1</wnks></row>
<row><type>ua</type><token>blogged_crawl</token><name>Blogged</name><wnks>1</wnks></row>
<row><type>ua</type><token>bloglines</token><name>Bloglines</name><wnks>1</wnks></row>
<row><type>ua</type><token>blogscope</token><name>BlogScope</name><wnks>1</wnks></row>
<row><type>ua</type><token>blogshares</token><name>BlogShares</name><wnks>1</wnks></row>
<row><type>ua</type><token>blogsnowbot</token><name>BlogsNow</name><wnks>1</wnks></row>
<row><type>ua</type><token>boardreader.com/info</token><name>BoardReader</name><wnks>1</wnks></row>
<row><type>ua</type><token>sync2it.com</token><name>Bookmark Sync2it</name><wnks>1</wnks></row>
<row><type>ua</type><token>booster</token><name>Booster</name><wnks>1</wnks></row>
<row><type>ua</type><token>brekiricrawler</token><name>Brekiri</name><wnks>1</wnks></row>
<row><type>ua</type><token>topsy.com/butterfly</token><name>Butterfly</name><wnks>1</wnks></row>
<row><type>ua</type><token>buzzrage</token><name>BuzzCore</name><wnks>1</wnks></row>
<row><type>ua</type><token>buzzrank</token><name>BuzzRank</name><wnks>1</wnks></row>
<row><type>ua</type><token>cctestbot</token><name>CCTestBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>cirrusexplorer</token><name>CirrusExplorer</name><wnks>1</wnks></row>
<row><type>ua</type><token>cmsworldmap.com</token><name>CMSWorldMap</name><wnks>1</wnks></row>
<row><type>ua</type><token>ccbot</token><name>CommonCrawl</name><wnks>1</wnks></row>
<row><type>ua</type><token>comodo</token><name>Comodo</name><wnks>1</wnks></row>
<row><type>ua</type><token>compspybot</token><name>CompSpy</name><wnks>1</wnks></row>
<row><type>ua</type><token>contextadbot</token><name>ContextAd</name><wnks>1</wnks></row>
<row><type>ua</type><token>crawler4j</token><name>Crawler4j</name><wnks>1</wnks></row>
<row><type>ua</type><token>curl/</token><name>cURL</name><wnks>1</wnks></row>
<row><type>ua</type><token>darwin</token><name>Darwin</name><wnks>1</wnks></row>
<row><type>ua</type><token>diffbot</token><name>DiffBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>discobot</token><name>Discobot</name><wnks>1</wnks></row>
<row><type>ua</type><token>discoverybot</token><name>Discovery</name><wnks>1</wnks></row>
<row><type>ua</type><token>docomo</token><name>DoCoMo</name><wnks>1</wnks></row>
<row><type>ua</type><token>donkeybot</token><name>DonkeyBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>dotbot</token><name>DotBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>easydl</token><name>EasyDL</name><wnks>1</wnks></row>
<row><type>ua</type><token>eventguru</token><name>EventGuru</name><wnks>1</wnks></row>
<row><type>ua</type><token>exabot</token><name>Exabot</name><wnks>1</wnks></row>
<row><type>ua</type><token>ezooms</token><name>eZooms</name><wnks>1</wnks></row>
<row><type>ua</type><token>facebookexternalhit</token><name>FaceBook</name><wnks>1</wnks></row>
<row><type>ua</type><token>fairshare</token><name>FairShare</name><wnks>1</wnks></row>
<row><type>ua</type><token>feed::find</token><name>Feed::Find</name><wnks>1</wnks></row>
<row><type>ua</type><token>feedburner</token><name>FeedBurner</name><wnks>1</wnks></row>
<row><type>ua</type><token>feedly.com</token><name>Feedly</name><wnks>1</wnks></row>
<row><type>ua</type><token>feedster</token><name>Feedster</name><wnks>1</wnks></row>
<row><type>ua</type><token>focusedcrawler</token><name>Focused</name><wnks>1</wnks></row>
<row><type>ua</type><token>friendlyrobot</token><name>Friendly</name><wnks>1</wnks></row>
<row><type>ua</type><token>fybersearch</token><name>FyberSpider</name><wnks>1</wnks></row>
<row><type>ua</type><token>galbot</token><name>Galbot</name><wnks>1</wnks></row>
<row><type>ua</type><token>garlikcrawler</token><name>Garlik</name><wnks>1</wnks></row>
<row><type>ua</type><token>genieo</token><name>Genieo</name><wnks>1</wnks></row>
<row><type>ua</type><token>gigablastopensource</token><name>Gigablast</name><wnks>1</wnks></row>
<row><type>ua</type><token>gigablast.com/spider</token><name>Gigabot</name><wnks>1</wnks></row>
<row><type>ua</type><token>gigabot</token><name>GigaBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>mediapartners-google</token><name>Google AdSense</name><wnks>1</wnks></row>
<row><type>ua</type><token>klipbot</token><name>Google Klipbot</name><wnks>1</wnks></row>
<row><type>ua</type><token>googlebot/2.1</token><name>Google/2.1</name><wnks>1</wnks></row>
<row><type>ua</type><token>appengine</token><name>GoogleAppengine</name><wnks>1</wnks></row>
<row><type>ua</type><token>googlebot-mobile/2.1</token><name>Googlebot-Mobile 2.1</name><wnks>1</wnks></row>
<row><type>ua</type><token>feedfetcher-google;</token><name>GoogleFeed</name><wnks>1</wnks></row>
<row><type>ua</type><token>google-sitemaps</token><name>GoogleSitemaps</name><wnks>1</wnks></row>
<row><type>ua</type><token>googlewebpreview</token><name>GoogleWebPreview</name><wnks>1</wnks></row>
<row><type>ua</type><token>goscraper</token><name>GoScraper</name><wnks>1</wnks></row>
<row><type>ua</type><token>grazr</token><name>Grazr</name><wnks>1</wnks></row>
<row><type>ua</type><token>grubng</token><name>Grub</name><wnks>1</wnks></row>
<row><type>ua</type><token>hailoobot</token><name>Hailoo</name><wnks>1</wnks></row>
<row><type>ua</type><token>harry</token><name>Harry</name><wnks>1</wnks></row>
<row><type>ua</type><token>harvest</token><name>Harvest</name><wnks>1</wnks></row>
<row><type>ua</type><token>heritrix</token><name>Heritrix</name><wnks>1</wnks></row>
<row><type>ua</type><token>huaweisymantec</token><name>Huaweisymantec</name><wnks>1</wnks></row>
<row><type>ua</type><token>blogsearch</token><name>Icerocket</name><wnks>1</wnks></row>
<row><type>ua</type><token>ichiro</token><name>ichiro</name><wnks>1</wnks></row>
<row><type>ua</type><token>icopyright</token><name>iCopyrightConductor</name><wnks>1</wnks></row>
<row><type>ua</type><token>inagist.com</token><name>InAGist</name><wnks>1</wnks></row>
<row><type>ua</type><token>infobot</token><name>Infobot</name><wnks>1</wnks></row>
<row><type>ua</type><token>insieve</token><name>Insieve</name><wnks>1</wnks></row>
<row><type>ua</type><token>integromedb</token><name>Integro</name><wnks>1</wnks></row>
<row><type>ua</type><token>imrbot</token><name>InternetMemory</name><wnks>1</wnks></row>
<row><type>ua</type><token>iscraperbot</token><name>IScraperBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>isense</token><name>iSense</name><wnks>1</wnks></row>
<row><type>ua</type><token>istellabot</token><name>Istella</name><wnks>1</wnks></row>
<row><type>ua</type><token>jaxified</token><name>Jaxified</name><wnks>1</wnks></row>
<row><type>ua</type><token>jspyda</token><name>JSpyda</name><wnks>1</wnks></row>
<row><type>ua</type><token>voyager</token><name>Kosmix</name><wnks>1</wnks></row>
<row><type>ua</type><token>larbin</token><name>Larbin</name><wnks>1</wnks></row>
<row><type>ua</type><token>largesmallcrawler</token><name>LargeSmall</name><wnks>1</wnks></row>
<row><type>ua</type><token>lemurwebcrawler</token><name>Lemur</name><wnks>1</wnks></row>
<row><type>ua</type><token>linguee</token><name>Linguee</name><wnks>1</wnks></row>
<row><type>ua</type><token>linkdex</token><name>LinkDex</name><wnks>1</wnks></row>
<row><type>ua</type><token>linkjumper</token><name>LinkJumper</name><wnks>1</wnks></row>
<row><type>ua</type><token>linkscrawler</token><name>LinksCrawler</name><wnks>1</wnks></row>
<row><type>ua</type><token>linkwalker</token><name>LinkWalker</name><wnks>1</wnks></row>
<row><type>ua</type><token>lipperhey</token><name>Lipperhey</name><wnks>1</wnks></row>
<row><type>ua</type><token>www.brandwatch.net</token><name>MagpieBrandwatch</name><wnks>1</wnks></row>
<row><type>ua</type><token>mail.ru_bot</token><name>Mail.RUBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>mj12bot</token><name>Majestic</name><wnks>1</wnks></row>
<row><type>ua</type><token>mandalay</token><name>Mandalay</name><wnks>1</wnks></row>
<row><type>ua</type><token>metalogger</token><name>Metalogger</name><wnks>1</wnks></row>
<row><type>ua</type><token>metamojicrawler</token><name>MetaMoji</name><wnks>1</wnks></row>
<row><type>ua</type><token>microsofturlcontrol</token><name>Microsoft URL Control</name><wnks>1</wnks></row>
<row><type>ua</type><token>minisearch_spider</token><name>MiniSearch</name><wnks>1</wnks></row>
<row><type>ua</type><token>metadatalabs.com/mlbot</token><name>MLBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>mnogosearch</token><name>MnoGoSearch</name><wnks>1</wnks></row>
<row><type>ua</type><token>mojeekbot</token><name>Mojeek</name><wnks>1</wnks></row>
<row><type>ua</type><token>moreoverbot</token><name>Moreover</name><wnks>1</wnks></row>
<row><type>ua</type><token>moreover</token><name>MoreOver</name><wnks>1</wnks></row>
<row><type>ua</type><token>mp3bot</token><name>MP3Realm</name><wnks>1</wnks></row>
<row><type>ua</type><token>msiecrawler</token><name>MSIECrawler</name><wnks>1</wnks></row>
<row><type>ua</type><token>bingbot/2.0</token><name>MSNBing</name><wnks>1</wnks></row>
<row><type>ua</type><token>msnbot-media/1.1</token><name>MSNMedia</name><wnks>1</wnks></row>
<row><type>ua</type><token>mssearch</token><name>MSSearch</name><wnks>1</wnks></row>
<row><type>ua</type><token>naver.com/robots</token><name>Naver</name><wnks>1</wnks></row>
<row><type>ua</type><token>neofonie</token><name>neofonie</name><wnks>1</wnks></row>
<row><type>ua</type><token>nesotebot</token><name>NesoteBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>netvibes.com</token><name>NetVibes</name><wnks>1</wnks></row>
<row><type>ua</type><token>;newsbot/</token><name>NewsBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>newzcrawler</token><name>Newzcrawler</name><wnks>1</wnks></row>
<row><type>ua</type><token>nigma.ru</token><name>Nigma</name><wnks>1</wnks></row>
<row><type>ua</type><token>nrsbot</token><name>NRSBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>nutch</token><name>Nutch</name><wnks>1</wnks></row>
<row><type>ua</type><token>oneriot.com</token><name>OneRiot</name><wnks>1</wnks></row>
<row><type>ua</type><token>openindex</token><name>OpenIndex</name><wnks>1</wnks></row>
<row><type>ua</type><token>oppo</token><name>OppO</name><wnks>1</wnks></row>
<row><type>ua</type><token>pagesinventory</token><name>PagesInventory</name><wnks>1</wnks></row>
<row><type>ua</type><token>paperlibot</token><name>PaperLi</name><wnks>1</wnks></row>
<row><type>ua</type><token>patchone.se</token><name>PatchOne</name><wnks>1</wnks></row>
<row><type>ua</type><token>123peoplebot</token><name>PeopleBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>www.nexen.net</token><name>PHP version tracker</name><wnks>1</wnks></row>
<row><type>ua</type><token>psbot</token><name>PicSearch</name><wnks>1</wnks></row>
<row><type>ua</type><token>pixray</token><name>Pixray</name><wnks>1</wnks></row>
<row><type>ua</type><token>postrank.com</token><name>PostRank</name><wnks>1</wnks></row>
<row><type>ua</type><token>printfulbot</token><name>PrintFul</name><wnks>1</wnks></row>
<row><type>ua</type><token>proximic</token><name>Proximic</name><wnks>1</wnks></row>
<row><type>ua</type><token>purebot</token><name>PureBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>queryseeker</token><name>QuerySeeker</name><wnks>1</wnks></row>
<row><type>ua</type><token>www.radian6.com/crawler</token><name>Radian6</name><wnks>1</wnks></row>
<row><type>ua</type><token>relevantnoise</token><name>relevantNOISE</name><wnks>1</wnks></row>
<row><type>ua</type><token>replazbot</token><name>Replaz</name><wnks>1</wnks></row>
<row><type>ua</type><token>riverglassscanner</token><name>RiverGlass</name><wnks>1</wnks></row>
<row><type>ua</type><token>rogerbot</token><name>RogerBot</name><wnks>1</wnks></row>
<row><type>ua</type><token>rssmicro.com</token><name>RSSMicro</name><wnks>1</wnks></row>
<row><type>ua</type><token>rssscout0.11.2</token><name>RSSScout</name><wnks>1</wnks></row>
<row><type>ua</type><token>runnk</token><name>Runnk</name><wnks>1</wnks></row>
<row><type>ua</type><token>sbider</token><name>SBider</name><wnks>1</wnks></row>
<row><type>ua</type><token>www.scoutjet.com</token><name>ScoutJet</name><wnks>1</wnks></row>
<row><type>ua</type><token>scrapy</token><name>Scrapy</name><wnks>1</wnks></row>
<row><type>ua</type><token>screamingfrog</token><name>ScreamingFrog</name><wnks>1</wnks></row>
<row><type>ua</type><token>search17bot</token><name>Search17</name><wnks>1</wnks></row>
<row><type>ua</type><token>searchme.com</token><name>Searchme.com</name><wnks>1</wnks></row>
<row><type>ua</type><token>searchmetricsbot</token><name>SearchMetrics</name><wnks>1</wnks></row>
<row><type>ua</type><token>semrushbot</token><name>SemRush</name><wnks>1</wnks></row>
<row><type>ua</type><token>seoengworldbot</token><name>SEOEngine</name><wnks>1</wnks></row>
<row><type>ua</type><token>seokicks</token><name>SEOKicks</name><wnks>1</wnks></row>
<row><type>ua</type><token>spbot</token><name>SEOProfiler</name><wnks>1</wnks></row>
<row><type>ua</type><token>seznambot</token><name>Seznam</name><wnks>1</wnks></row>
<row><type>ua</type><token>shelob</token><name>shelob</name><wnks>1</wnks></row>
<row><type>ua</type><token>showyoubot</token><name>ShowYou</name><wnks>1</wnks></row>
<row><type>ua</type><token>similarpages</token><name>SimilarPages</name><wnks>1</wnks></row>
<row><type>ua</type><token>simplepie</token><name>SimplePie</name><wnks>1</wnks></row>
<row><type>ua</type><token>sindice-fetcher</token><name>Sindice</name><wnks>1</wnks></row>
<row><type>ua</type><token>sistrix.net</token><name>Sistrix</name><wnks>1</wnks></row>
<row><type>ua</type><token>siteexplorer</token><name>SiteExplorer</name><wnks>1</wnks></row>
<row><type>ua</type><token>slugbug.com</token><name>SlugBug</name><wnks>1</wnks></row>
<row><type>ua</type><token>snap</token><name>Snapbot</name><wnks>1</wnks></row>
<row><type>ua</type><token>snoopy</token><name>Snoopy</name><wnks>1</wnks></row>
<row><type>ua</type><token>socialayer.com</token><name>SocialLayer</name><wnks>1</wnks></row>
<row><type>ua</type><token>socialmediaminer</token><name>SocialMediaMiner</name><wnks>1</wnks></row>
<row><type>ua</type><token>socialradarbot</token><name>SocialRadar</name><wnks>1</wnks></row>
<row><type>ua</type><token>socialsearcher</token><name>SocialSearcher</name><wnks>1</wnks></row>
<row><type>ua</type><token>speedyspider</token><name>SpeedySpider</name><wnks>1</wnks></row>
<row><type>ua</type><token>www.sphere.com</token><name>Sphere</name><wnks>1</wnks></row>
<row><type>ua</type><token>spiderling</token><name>SpiderLing</name><wnks>1</wnks></row>
<row><type>ua</type><token>spinn3r.com/robot</token><name>Spinn3r</name><wnks>1</wnks></row>
<row><type>ua</type><token>stackrambler</token><name>StackRambler</name><wnks>1</wnks></row>
<row><type>ua</type><token>steeler</token><name>Steeler</name><wnks>1</wnks></row>
<row><type>ua</type><token>stumbleupon</token><name>StumbleUpon</name><wnks>1</wnks></row>
<row><type>ua</type><token>surphace</token><name>Surphace</name><wnks>1</wnks></row>
<row><type>ua</type><token>synapse</token><name>Synapse</name><wnks>1</wnks></row>
<row><type>ua</type><token>tailrank</token><name>Tailrank</name><wnks>1</wnks></row>
<row><type>ua</type><token>tailsweep</token><name>Tailsweep</name><wnks>1</wnks></row>
<row><type>ua</type><token>technoratibot</token><name>Technorati</name><wnks>1</wnks></row>
<row><type>ua</type><token>techrigy</token><name>Techrigy</name><wnks>1</wnks></row>
<row><type>ua</type><token>testwebbot</token><name>TestWeb</name><wnks>1</wnks></row>
<row><type>ua</type><token>thriceler</token><name>Thriceler</name><wnks>1</wnks></row>
<row><type>ua</type><token>trendictionbot</token><name>Trendiction</name><wnks>1</wnks></row>
<row><type>ua</type><token>turnitinbot</token><name>Turnitin</name><wnks>1</wnks></row>
<row><type>ua</type><token>tweetmemebot</token><name>TweetMeme</name><wnks>1</wnks></row>
<row><type>ua</type><token>twinglyrecon</token><name>Twingly</name><wnks>1</wnks></row>
<row><type>ua</type><token>twitterbot</token><name>Twitterbot</name><wnks>1</wnks></row>
<row><type>ua</type><token>twitturls.com</token><name>Twitturls</name><wnks>1</wnks></row>
<row><type>ua</type><token>twitturly</token><name>Twitturly</name><wnks>1</wnks></row>
<row><type>ua</type><token>umbot-ln</token><name>UberMetrics</name><wnks>1</wnks></row>
<row><type>ua</type><token>unisterbot</token><name>Unister</name><wnks>1</wnks></row>
<row><type>ua</type><token>universalfeedparser</token><name>UniversalFeedParser</name><wnks>1</wnks></row>
<row><type>ua</type><token>unwindfetchor</token><name>UnwindFetchor</name><wnks>1</wnks></row>
<row><type>ua</type><token>uri::fetch</token><name>URI::Fetch</name><wnks>1</wnks></row>
<row><type>ua</type><token>w3c_validator</token><name>W3C Validator</name><wnks>1</wnks></row>
<row><type>ua</type><token>wbsearchbot</token><name>WBSearch</name><wnks>1</wnks></row>
<row><type>ua</type><token>webarchiving</token><name>webarchiving</name><wnks>1</wnks></row>
<row><type>ua</type><token>webcollage</token><name>WebCollage</name><wnks>1</wnks></row>
<row><type>ua</type><token>webcurator</token><name>WebCurator</name><wnks>1</wnks></row>
<row><type>ua</type><token>weblyzard</token><name>webLyzard</name><wnks>1</wnks></row>
<row><type>ua</type><token>webnl</token><name>WebNL</name><wnks>1</wnks></row>
<row><type>ua</type><token>webscout</token><name>WebScout</name><wnks>1</wnks></row>
<row><type>ua</type><token>wells</token><name>Wells Search</name><wnks>1</wnks></row>
<row><type>ua</type><token>whitevector</token><name>Whitevector</name><wnks>1</wnks></row>
<row><type>ua</type><token>wordchampbot</token><name>WordChamp</name><wnks>1</wnks></row>
<row><type>ua</type><token>xenulink</token><name>Xenu Link Sleuth</name><wnks>1</wnks></row>
<row><type>ua</type><token>yacybot</token><name>Yacy</name><wnks>1</wnks></row>
<row><type>ua</type><token>yahoo!slurp</token><name>Yahoo!</name><wnks>1</wnks></row>
<row><type>ua</type><token>yahoofeedseeker</token><name>YahooFeedSeeker</name><wnks>1</wnks></row>
<row><type>ua</type><token>yamanalab</token><name>YamanaLab</name><wnks>1</wnks></row>
<row><type>ua</type><token>yandex</token><name>Yandex</name><wnks>1</wnks></row>
</table>
